#spring.profiles.active=dev
#spring.application.name=Mobile Banking
#liquibase.change-log=classpath:liquibase/db.changelog-master.xml

spring:
    application:
            name: Mobile Banking
    profiles:
        active: dev

liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml

#spring.datasource.url=jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf8&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#security.require_ssl=false

#jwt.header=Authorization
#jwt.secret=LogateSecretKey
#jwt.expiration=604800